// Copyright 2026 MacPaw Way Ltd.
//
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
//
//        http://www.apache.org/licenses/LICENSE-2.0
//
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.
//
// RawWeightsParityTests.swift
// Tests that load raw PyTorch weights (no conversion script) and verify
// end-to-end inference parity with Python GLiNER2 predictions.
//
// These tests verify that Extractor.sanitize() correctly remaps raw
// PyTorch snake_case keys to the camelCase format expected by Swift modules.

import XCTest
import Foundation
import Metal
@testable import GLiNER2Swift
import MLX
import MLXNN

/// Tests that load raw PyTorch model.safetensors and compare inference results
/// against Python-generated fixtures.
///
/// Requirements:
/// - Raw weights at: gliner2-base-v1/model.safetensors (from HuggingFace)
/// - Fixtures at: Fixtures/raw_weights/*.json (generated by generate_raw_weights_fixtures.py)
/// - Metal GPU access (for MLX)
final class RawWeightsParityTests: XCTestCase {

    // Path to raw HuggingFace model (not converted by convert_weights.py)
    static let rawModelPath = {
        // Try relative to repo root
        let candidates = [
            // From env var
            ProcessInfo.processInfo.environment["GLINER2_MODEL_PATH"],
            // Relative to project root
            URL(fileURLWithPath: #file)
                .deletingLastPathComponent()
                .deletingLastPathComponent()
                .deletingLastPathComponent()
                .appendingPathComponent("gliner2-base-v1").path,
        ].compactMap { $0 }
        for path in candidates {
            if FileManager.default.fileExists(atPath: path + "/model.safetensors") {
                return path
            }
        }
        return candidates[0]
    }()

    // Path to fixtures
    static let fixturesPath: String = {
        let testFile = URL(fileURLWithPath: #file)
        return testFile.deletingLastPathComponent()
            .appendingPathComponent("Fixtures/raw_weights")
            .path
    }()

    // MARK: - Helpers

    private func skipIfNoGPU() throws {
        guard MTLCreateSystemDefaultDevice() != nil else {
            throw XCTSkip("Metal GPU not available")
        }
    }

    private func skipIfNoModel() throws {
        guard FileManager.default.fileExists(atPath: Self.rawModelPath + "/model.safetensors") else {
            throw XCTSkip("Raw model not available at \(Self.rawModelPath)")
        }
    }

    private func skipIfNoFixtures() throws {
        guard FileManager.default.fileExists(atPath: Self.fixturesPath) else {
            throw XCTSkip("Fixtures not available at \(Self.fixturesPath)")
        }
    }

    private func loadFixtureJSON(_ name: String) throws -> [String: Any] {
        let url = URL(fileURLWithPath: Self.fixturesPath).appendingPathComponent("\(name).json")
        let data = try Data(contentsOf: url)
        guard let json = try JSONSerialization.jsonObject(with: data) as? [String: Any] else {
            throw NSError(domain: "RawWeightsParityTests", code: 1,
                          userInfo: [NSLocalizedDescriptionKey: "Failed to parse \(name).json"])
        }
        return json
    }

    private func loadModel() async throws -> GLiNER2 {
        try await GLiNER2.fromPretrained(Self.rawModelPath)
    }

    // MARK: - Sanitize Unit Tests

    func testSanitizeDetectsRawFormat() throws {
        let rawWeights: [String: MLXArray] = [
            "span_rep.span_rep_layer.project_start.0.weight": MLXArray.zeros([1]),
            "encoder.embeddings.word_embeddings.weight": MLXArray.zeros([1]),
        ]
        let result = Extractor.sanitize(weights: rawWeights)
        // Should remap span_rep key
        XCTAssertNotNil(result["spanRep.spanRepLayer.projectStart.0.weight"])
        // Encoder key should pass through
        XCTAssertNotNil(result["encoder.embeddings.word_embeddings.weight"])
        // Original raw key should be gone
        XCTAssertNil(result["span_rep.span_rep_layer.project_start.0.weight"])
    }

    func testSanitizePassesThroughConvertedFormat() throws {
        let convertedWeights: [String: MLXArray] = [
            "spanRep.spanRepLayer.projectStart.0.weight": MLXArray.zeros([1]),
            "encoder.embeddings.word_embeddings.weight": MLXArray.zeros([1]),
        ]
        let result = Extractor.sanitize(weights: convertedWeights)
        // Should be identical (no span_rep. keys = not raw format)
        XCTAssertNotNil(result["spanRep.spanRepLayer.projectStart.0.weight"])
        XCTAssertNotNil(result["encoder.embeddings.word_embeddings.weight"])
    }

    func testSanitizeAllKeyMappings() throws {
        // Test all key mappings from the sanitize method
        let testMappings: [(String, String)] = [
            ("span_rep.span_rep_layer.project_start.0.weight", "spanRep.spanRepLayer.projectStart.0.weight"),
            ("span_rep.span_rep_layer.project_end.3.bias", "spanRep.spanRepLayer.projectEnd.3.bias"),
            ("span_rep.span_rep_layer.out_project.0.weight", "spanRep.spanRepLayer.outProject.0.weight"),
            ("classifier.0.weight", "classifier.layers.0.weight"),
            ("classifier.2.bias", "classifier.layers.1.bias"),
            ("count_pred.0.weight", "countPred.layers.0.weight"),
            ("count_pred.2.bias", "countPred.layers.1.bias"),
            ("count_embed.pos_embedding.weight", "countEmbed.posEmbedding.weight"),
            ("count_embed.gru.weight_ih_l0", "countEmbed.gru.weightIH"),
            ("count_embed.gru.weight_hh_l0", "countEmbed.gru.weightHH"),
            ("count_embed.gru.bias_ih_l0", "countEmbed.gru.biasIH"),
            ("count_embed.gru.bias_hh_l0", "countEmbed.gru.biasHH"),
            ("count_embed.transformer.in_projector.weight", "countEmbed.transformer.inProjector.weight"),
            ("count_embed.transformer.out_projector.0.weight", "countEmbed.transformer.outProjector.0.weight"),
            ("count_embed.transformer.transformer.layers.0.self_attn.in_proj_weight",
             "countEmbed.transformer.transformerLayers.0.self_attn.in_proj_weight"),
            ("encoder.encoder.layer.0.attention.self.query_proj.weight",
             "encoder.encoder.layer.0.attention.self.query_proj.weight"),
        ]

        // Build a weights dict with all raw keys
        var rawWeights: [String: MLXArray] = [:]
        for (rawKey, _) in testMappings {
            rawWeights[rawKey] = MLXArray.zeros([1])
        }

        let result = Extractor.sanitize(weights: rawWeights)

        for (rawKey, expectedKey) in testMappings {
            XCTAssertNotNil(result[expectedKey],
                "Key mapping failed: '\(rawKey)' should map to '\(expectedKey)'. Keys: \(result.keys.sorted())")
            // Encoder keys pass through unchanged (rawKey == expectedKey), so skip nil check
            if rawKey != expectedKey {
                XCTAssertNil(result[rawKey],
                    "Raw key '\(rawKey)' should not remain after sanitize")
            }
        }
    }

    // MARK: - Weight Loading Test

    func testLoadRawWeightsDoesNotCrash() async throws {
        try skipIfNoGPU()
        try skipIfNoModel()

        let model = try await loadModel()
        XCTAssertNotNil(model)

        // Verify classifier weights are loaded (not random zeros)
        let classifierWeight = model.model.classifier.layers[0] as! Linear
        let weightSum = MLX.sum(MLX.abs(classifierWeight.weight))
        MLX.eval(weightSum)
        XCTAssertGreaterThan(Float(weightSum.item(Float32.self)), 0.0,
            "Classifier weights should not be all zeros after loading raw weights")
    }

    // MARK: - Entity Extraction Parity

    func testEntityBasicParity() async throws {
        try skipIfNoGPU()
        try skipIfNoModel()
        try skipIfNoFixtures()

        let model = try await loadModel()
        let expected = try loadFixtureJSON("entity_basic_result")

        let result = model.extractEntities(
            text: "Tim Cook is CEO of Apple.",
            entityTypes: ["person", "company"],
            threshold: 0.5,
            includeConfidence: true,
            includeSpans: true
        )

        // Compare entity results
        guard let expectedEntities = expected["entities"] as? [String: Any],
              let resultEntities = result["entities"] as? [String: Any] else {
            XCTFail("Missing 'entities' key in result")
            return
        }

        // Check person entities
        assertEntityListMatch(
            resultEntities["person"], expectedEntities["person"],
            entityType: "person"
        )

        // Check company entities
        assertEntityListMatch(
            resultEntities["company"], expectedEntities["company"],
            entityType: "company"
        )
    }

    func testEntityMultiParity() async throws {
        try skipIfNoGPU()
        try skipIfNoModel()
        try skipIfNoFixtures()

        let model = try await loadModel()
        let expected = try loadFixtureJSON("entity_multi_result")

        let result = model.extractEntities(
            text: "John and Jane work at Google in Mountain View.",
            entityTypes: ["person", "organization", "location"],
            threshold: 0.5,
            includeConfidence: true,
            includeSpans: true
        )

        guard let expectedEntities = expected["entities"] as? [String: Any],
              let resultEntities = result["entities"] as? [String: Any] else {
            XCTFail("Missing 'entities' key")
            return
        }

        for entityType in ["person", "organization", "location"] {
            assertEntityListMatch(
                resultEntities[entityType], expectedEntities[entityType],
                entityType: entityType
            )
        }
    }

    func testEntityNoMatchParity() async throws {
        try skipIfNoGPU()
        try skipIfNoModel()
        try skipIfNoFixtures()

        let model = try await loadModel()
        let expected = try loadFixtureJSON("entity_no_match_result")

        let result = model.extractEntities(
            text: "The weather is nice today.",
            entityTypes: ["person", "company"],
            threshold: 0.5,
            includeConfidence: true,
            includeSpans: true
        )

        guard let expectedEntities = expected["entities"] as? [String: Any],
              let resultEntities = result["entities"] as? [String: Any] else {
            XCTFail("Missing 'entities' key")
            return
        }

        // Both should be empty
        for entityType in ["person", "company"] {
            let expectedList = expectedEntities[entityType] as? [Any] ?? []
            let resultList = resultEntities[entityType] as? [Any] ?? []
            XCTAssertEqual(resultList.count, expectedList.count,
                "Entity type '\(entityType)' count mismatch: got \(resultList.count), expected \(expectedList.count)")
        }
    }

    // MARK: - Classification Parity

    func testClassifySentimentPositiveParity() async throws {
        try skipIfNoGPU()
        try skipIfNoModel()
        try skipIfNoFixtures()

        let model = try await loadModel()
        let expected = try loadFixtureJSON("classify_sentiment_positive_result")

        let result = model.classifyText(
            text: "Great product! I love it.",
            task: "sentiment",
            labels: ["positive", "negative", "neutral"],
            threshold: 0.5,
            includeConfidence: true
        )

        assertClassificationMatch(result, expected, task: "sentiment")
    }

    func testClassifySentimentNegativeParity() async throws {
        try skipIfNoGPU()
        try skipIfNoModel()
        try skipIfNoFixtures()

        let model = try await loadModel()
        let expected = try loadFixtureJSON("classify_sentiment_negative_result")

        let result = model.classifyText(
            text: "Terrible service. Very disappointed.",
            task: "sentiment",
            labels: ["positive", "negative", "neutral"],
            threshold: 0.5,
            includeConfidence: true
        )

        assertClassificationMatch(result, expected, task: "sentiment")
    }

    // MARK: - Structure Extraction Parity

    func testStructPersonParity() async throws {
        try skipIfNoGPU()
        try skipIfNoModel()
        try skipIfNoFixtures()

        let model = try await loadModel()
        let expected = try loadFixtureJSON("struct_person_result")

        let schema = model.createSchema()
            .structure("person_info")
            .field("name")
            .field("age")
            .field("location")
            .done()

        let result = model.extract(
            text: "John Smith is 35 years old and lives in New York.",
            schema: schema,
            threshold: 0.5,
            includeConfidence: true,
            includeSpans: true
        )

        assertStructureMatch(result, expected, structureName: "person_info",
                             fields: ["name", "age", "location"])
    }

    func testStructProductParity() async throws {
        try skipIfNoGPU()
        try skipIfNoModel()
        try skipIfNoFixtures()

        let model = try await loadModel()
        let expected = try loadFixtureJSON("struct_product_result")

        let schema = model.createSchema()
            .structure("product")
            .field("name")
            .field("price")
            .field("manufacturer")
            .done()

        let result = model.extract(
            text: "iPhone 15 Pro costs $999 and is made by Apple.",
            schema: schema,
            threshold: 0.5,
            includeConfidence: true,
            includeSpans: true
        )

        assertStructureMatch(result, expected, structureName: "product",
                             fields: ["name", "price", "manufacturer"])
    }

    // MARK: - Assertion Helpers

    private func assertEntityListMatch(_ result: Any?, _ expected: Any?, entityType: String) {
        guard let expectedList = expected as? [[String: Any]] else {
            XCTFail("Expected list missing for entity type '\(entityType)'")
            return
        }

        guard let resultList = result as? [[String: Any]] else {
            // Could be empty array of strings
            if let resultStrList = result as? [String] {
                XCTAssertEqual(resultStrList.count, expectedList.count,
                    "Entity '\(entityType)' count mismatch")
                return
            }
            if let resultEmpty = result as? [Any], resultEmpty.isEmpty, expectedList.isEmpty {
                return  // Both empty
            }
            XCTFail("Result type mismatch for entity type '\(entityType)': \(type(of: result))")
            return
        }

        XCTAssertEqual(resultList.count, expectedList.count,
            "Entity '\(entityType)' count: got \(resultList.count), expected \(expectedList.count)")

        for (i, expectedEntity) in expectedList.enumerated() {
            guard i < resultList.count else { break }
            let resultEntity = resultList[i]

            let expectedText = expectedEntity["text"] as? String ?? ""
            let resultText = resultEntity["text"] as? String ?? ""
            XCTAssertEqual(resultText, expectedText,
                "Entity '\(entityType)' [\(i)] text: got '\(resultText)', expected '\(expectedText)'")

            if let expectedStart = expectedEntity["start"] as? Int,
               let resultStart = resultEntity["start"] as? Int {
                XCTAssertEqual(resultStart, expectedStart,
                    "Entity '\(entityType)' [\(i)] start: got \(resultStart), expected \(expectedStart)")
            }

            if let expectedEnd = expectedEntity["end"] as? Int,
               let resultEnd = resultEntity["end"] as? Int {
                XCTAssertEqual(resultEnd, expectedEnd,
                    "Entity '\(entityType)' [\(i)] end: got \(resultEnd), expected \(expectedEnd)")
            }
        }
    }

    private func assertClassificationMatch(_ result: [String: Any], _ expected: [String: Any], task: String) {
        guard let expectedTaskResult = expected[task] as? [String: Any],
              let expectedLabel = expectedTaskResult["label"] as? String else {
            XCTFail("Expected classification result missing for task '\(task)'")
            return
        }

        // Result can be nested: {"sentiment": {"label": "positive", "confidence": 1.0}}
        // Or flat: {"sentiment": "positive"}
        if let resultTaskResult = result[task] as? [String: Any],
           let resultLabel = resultTaskResult["label"] as? String {
            XCTAssertEqual(resultLabel, expectedLabel,
                "Classification '\(task)' label: got '\(resultLabel)', expected '\(expectedLabel)'")
        } else if let resultLabel = result[task] as? String {
            XCTAssertEqual(resultLabel, expectedLabel,
                "Classification '\(task)' label: got '\(resultLabel)', expected '\(expectedLabel)'")
        } else {
            XCTFail("Classification result type mismatch for task '\(task)': \(result)")
        }
    }

    private func assertStructureMatch(_ result: [String: Any], _ expected: [String: Any],
                                       structureName: String, fields: [String]) {
        guard let expectedInstances = expected[structureName] as? [[String: Any]] else {
            XCTFail("Expected structure instances missing for '\(structureName)'")
            return
        }

        guard let resultInstances = result[structureName] as? [[String: Any]] else {
            XCTFail("Result structure instances missing for '\(structureName)'. Got: \(result)")
            return
        }

        XCTAssertEqual(resultInstances.count, expectedInstances.count,
            "Structure '\(structureName)' instance count: got \(resultInstances.count), expected \(expectedInstances.count)")

        for (i, expectedInst) in expectedInstances.enumerated() {
            guard i < resultInstances.count else { break }
            let resultInst = resultInstances[i]

            for field in fields {
                // Each field is an array of span results
                guard let expectedFieldList = expectedInst[field] as? [[String: Any]] else { continue }
                guard let resultFieldList = resultInst[field] as? [[String: Any]] else {
                    XCTFail("Structure '\(structureName)' instance \(i) field '\(field)' missing in result")
                    continue
                }

                XCTAssertEqual(resultFieldList.count, expectedFieldList.count,
                    "Structure '\(structureName)' [\(i)].\(field) count: got \(resultFieldList.count), expected \(expectedFieldList.count)")

                for (j, expectedItem) in expectedFieldList.enumerated() {
                    guard j < resultFieldList.count else { break }
                    let resultItem = resultFieldList[j]

                    let expectedText = expectedItem["text"] as? String ?? ""
                    let resultText = resultItem["text"] as? String ?? ""
                    XCTAssertEqual(resultText, expectedText,
                        "Structure '\(structureName)' [\(i)].\(field)[\(j)] text: got '\(resultText)', expected '\(expectedText)'")
                }
            }
        }
    }
}
