// Copyright 2026 MacPaw Way Ltd.
//
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
//
//        http://www.apache.org/licenses/LICENSE-2.0
//
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.
//
// RegexEngineParityTests.swift
// Parity tests: Swift NSRegularExpression vs Python `re` on a shared matrix.
//
// Catches engine-level divergences on the intersection of syntactic features
// both engines support. Patterns that behave differently (variable-width
// lookbehind, possessive quantifiers, atomic groups) are excluded by design —
// they're rejected at RegexValidator.init-time or by ICU itself.
//
// Fixture generated by: scripts/generate_inference_fixtures.py

import XCTest
import Foundation
@testable import GLiNER2Swift

final class RegexEngineParityTests: XCTestCase {

    private func loadMatrix() throws -> [String: Any] {
        let url = URL(fileURLWithPath: #file)
            .deletingLastPathComponent()
            .appendingPathComponent("Fixtures")
            .appendingPathComponent("inference")
            .appendingPathComponent("regex_engine_matrix.json")

        guard FileManager.default.fileExists(atPath: url.path) else {
            throw XCTSkip("Fixture regex_engine_matrix.json not found — run scripts/generate_inference_fixtures.py")
        }

        let data = try Data(contentsOf: url)
        guard let json = try JSONSerialization.jsonObject(with: data) as? [String: Any] else {
            throw NSError(domain: "RegexEngineParityTests", code: 1)
        }
        return json
    }

    func testPythonReVsNSRegularExpressionMatrix() throws {
        let fixture = try loadMatrix()

        guard let patterns = fixture["patterns"] as? [[String: Any]],
              let texts = fixture["texts"] as? [String],
              let results = fixture["results"] as? [[Bool]]
        else {
            XCTFail("Malformed fixture")
            return
        }

        XCTAssertEqual(patterns.count, results.count)

        var divergences: [String] = []

        for (i, patternSpec) in patterns.enumerated() {
            guard let pattern = patternSpec["pattern"] as? String,
                  let modeStr = patternSpec["mode"] as? String
            else { continue }

            let mode: RegexValidator.MatchMode = (modeStr == "full") ? .full : .partial
            let validator: RegexValidator
            do {
                validator = try RegexValidator(pattern: pattern, mode: mode)
            } catch {
                XCTFail("Pattern \(pattern.debugDescription) rejected by Swift: \(error)")
                continue
            }

            let expectedRow = results[i]
            XCTAssertEqual(expectedRow.count, texts.count)

            for (j, text) in texts.enumerated() {
                let swiftMatched = validator.validate(text)
                let pythonMatched = expectedRow[j]

                if swiftMatched != pythonMatched {
                    divergences.append(
                        "pattern=\(pattern.debugDescription) mode=\(modeStr) " +
                        "text=\(text.debugDescription): Swift=\(swiftMatched) Python=\(pythonMatched)"
                    )
                }
            }
        }

        if !divergences.isEmpty {
            XCTFail("Engine parity divergences:\n" + divergences.joined(separator: "\n"))
        }
    }
}