// Copyright 2026 MacPaw Way Ltd.
//
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
//
//        http://www.apache.org/licenses/LICENSE-2.0
//
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.
//
// RegexValidatorParityTests.swift
// Parity tests for RegexValidator filter logic and schema-builder plumbing.
//
// Verifies:
// 1. Array<ExtractedSpan>.filtered(by:) produces the same output as Python's
//    post-threshold validator filter (engine.py:880-881) across a matrix of
//    cases including list/str dtype, exclude mode, AND-logic, rejects-all.
// 2. StructureBuilder.field(validators:) persists validators into
//    schema.metadata.fieldMetadata so the extraction path at GLiNER2.swift:1090
//    receives them. Mirrors Python _store_field_metadata (engine.py:154-160).
//
// Fixture generated by: scripts/generate_inference_fixtures.py

import XCTest
import Foundation
@testable import GLiNER2Swift

final class RegexValidatorParityTests: XCTestCase {

    // MARK: - Fixture loading

    private func loadCases() throws -> [[String: Any]] {
        let url = URL(fileURLWithPath: #file)
            .deletingLastPathComponent()
            .appendingPathComponent("Fixtures")
            .appendingPathComponent("inference")
            .appendingPathComponent("validator_filter_cases.json")

        guard FileManager.default.fileExists(atPath: url.path) else {
            throw XCTSkip("Fixture validator_filter_cases.json not found — run scripts/generate_inference_fixtures.py")
        }

        let data = try Data(contentsOf: url)
        guard let json = try JSONSerialization.jsonObject(with: data) as? [String: Any],
              let cases = json["cases"] as? [[String: Any]]
        else {
            throw NSError(domain: "RegexValidatorParityTests", code: 1)
        }
        return cases
    }

    private func buildValidators(_ specs: [[String: Any]]) throws -> [RegexValidator] {
        return try specs.map { spec in
            guard let pattern = spec["pattern"] as? String,
                  let modeStr = spec["mode"] as? String,
                  let exclude = spec["exclude"] as? Bool
            else {
                throw NSError(domain: "ValidatorSpec", code: 1)
            }
            let mode: RegexValidator.MatchMode = (modeStr == "full") ? .full : .partial
            return try RegexValidator(pattern: pattern, mode: mode, exclude: exclude)
        }
    }

    private func buildSpans(_ specs: [[String: Any]]) -> [ExtractedSpan] {
        return specs.compactMap { spec in
            guard let text = spec["text"] as? String,
                  let conf = (spec["confidence"] as? NSNumber)?.floatValue,
                  let start = spec["charStart"] as? Int,
                  let end = spec["charEnd"] as? Int
            else { return nil }
            return ExtractedSpan(text: text, confidence: conf, charStart: start, charEnd: end)
        }
    }

    // MARK: - Filter parity

    func testFilterParityAcrossAllCases() throws {
        let cases = try loadCases()

        for testCase in cases {
            guard let name = testCase["name"] as? String,
                  let validatorSpecs = testCase["validators"] as? [[String: Any]],
                  let spanSpecs = testCase["spans"] as? [[String: Any]],
                  let filteredSpecs = testCase["filtered"] as? [[String: Any]]
            else {
                XCTFail("Malformed case"); return
            }

            let validators = try buildValidators(validatorSpecs)
            let inputSpans = buildSpans(spanSpecs)
            let expectedSpans = buildSpans(filteredSpecs)

            let actual = inputSpans.filtered(by: validators)

            XCTAssertEqual(
                actual.count, expectedSpans.count,
                "\(name): span count mismatch — Swift=\(actual.count) Python=\(expectedSpans.count)"
            )

            let actualTexts = actual.map { $0.text }
            let expectedTexts = expectedSpans.map { $0.text }
            XCTAssertEqual(
                actualTexts, expectedTexts,
                "\(name): filtered span texts diverge"
            )

            // Also verify ordering is preserved (Python list comprehension preserves order).
            for (a, e) in zip(actual, expectedSpans) {
                XCTAssertEqual(a.text, e.text, "\(name): order divergence")
                XCTAssertEqual(a.charStart, e.charStart, "\(name): charStart divergence for \(a.text)")
                XCTAssertEqual(a.charEnd, e.charEnd, "\(name): charEnd divergence for \(a.text)")
            }
        }
    }

    // MARK: - Schema builder plumbing

    func testStructureBuilderPersistsValidatorsToMetadata() throws {
        let emailValidator = try RegexValidator(
            pattern: #"^[\w\.-]+@[\w\.-]+\.\w+$"#,
            mode: .full
        )
        let excludeTest = try RegexValidator(
            pattern: #"^(test|demo)"#,
            mode: .partial,
            exclude: true
        )

        let schema = Schema()
            .structure("contact")
            .field("email", dtype: "str", validators: [emailValidator])
            .field("username", dtype: "list", validators: [excludeTest])
            .field("notes", dtype: "str")  // no validators
            .done()

        let emailMeta = schema.metadata.fieldMetadata["contact.email"]
        XCTAssertNotNil(emailMeta, "email metadata must be populated")
        XCTAssertEqual(emailMeta?.validators.count, 1)
        XCTAssertEqual(emailMeta?.dtype, "str")

        let usernameMeta = schema.metadata.fieldMetadata["contact.username"]
        XCTAssertNotNil(usernameMeta)
        XCTAssertEqual(usernameMeta?.validators.count, 1)
        XCTAssertEqual(usernameMeta?.dtype, "list")

        let notesMeta = schema.metadata.fieldMetadata["contact.notes"]
        XCTAssertNotNil(notesMeta, "metadata must be populated for fields without validators too")
        XCTAssertEqual(notesMeta?.validators.count, 0)
    }

    // MARK: - Empty validators no-op

    func testEmptyValidatorsIsNoOp() throws {
        let spans = [
            ExtractedSpan(text: "anything", confidence: 0.9, charStart: 0, charEnd: 8),
            ExtractedSpan(text: "goes", confidence: 0.8, charStart: 10, charEnd: 14),
        ]
        let result = spans.filtered(by: [])
        XCTAssertEqual(result.count, 2)
    }

    // MARK: - Unsupported construct guard

    func testUnsupportedConstructThrowsOnInit() {
        // Atomic group — semantics diverge between Python 3.11+ and ICU.
        XCTAssertThrowsError(try RegexValidator(pattern: "(?>abc)", mode: .partial)) { error in
            guard case RegexValidatorError.unsupportedConstruct = error else {
                XCTFail("Expected unsupportedConstruct, got \(error)")
                return
            }
        }

        // Possessive quantifier.
        XCTAssertThrowsError(try RegexValidator(pattern: "a*+", mode: .partial)) { error in
            guard case RegexValidatorError.unsupportedConstruct = error else {
                XCTFail("Expected unsupportedConstruct, got \(error)")
                return
            }
        }
    }
}